import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import ClientOnly from '@/components/ClientOnly'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mokomoko',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
      <ClientOnly>
        <Navbar />
      </ClientOnly>
    </html>
  )
}
